# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-07 07:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=128, verbose_name='分类标题')),
                ('label', models.CharField(blank=True, max_length=128, null=True, verbose_name='分类标签')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/question/category/', verbose_name='分类图片')),
                ('order', models.PositiveSmallIntegerField(default=1, help_text='该分类在列表中的顺序', verbose_name='顺序')),
                ('remarks', models.TextField(blank=True, help_text='请输入这类行测试的描述等', null=True, verbose_name='备注、描述')),
            ],
            options={
                'verbose_name_plural': '测试类别',
                'ordering': ['order'],
                'verbose_name': '测试类别',
            },
        ),
        migrations.CreateModel(
            name='Inducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=128, verbose_name='类型名称')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/question/inducation/', verbose_name='类型卡片')),
                ('descp', models.TextField(blank=True, null=True, verbose_name='类型描述')),
                ('order', models.PositiveSmallIntegerField(default=1, help_text='该类型在分类列表中的顺序', verbose_name='顺序')),
            ],
            options={
                'verbose_name_plural': '结果分类',
                'ordering': ['order'],
                'verbose_name': '结果分类',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=128, verbose_name='选项')),
                ('descp', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('order', models.PositiveSmallIntegerField(default=1, help_text='该选项在列表中的顺序', verbose_name='顺序')),
            ],
            options={
                'verbose_name_plural': '题目选项',
                'ordering': ['order'],
                'verbose_name': '题目选项',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('number', models.PositiveSmallIntegerField(default=1, help_text='题目的题号', verbose_name='题号')),
                ('stem', models.CharField(max_length=512, verbose_name='题干')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('inducation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_inducation', to='question.Inducation', verbose_name='所属结果分类')),
            ],
            options={
                'verbose_name_plural': '题目',
                'ordering': ['number'],
                'verbose_name': '题目',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=128, verbose_name='测试名称')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/question/test/', verbose_name='测试介绍图片')),
                ('descp', models.TextField(blank=True, null=True, verbose_name='测试描述')),
                ('order', models.PositiveSmallIntegerField(default=1, help_text='该测试在测试列表中的顺序', verbose_name='顺序')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_category', to='question.Category', verbose_name='所属测试类别')),
            ],
            options={
                'verbose_name_plural': '测试',
                'ordering': ['order'],
                'verbose_name': '测试',
            },
        ),
        migrations.AddField(
            model_name='option',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_test', to='question.Test', verbose_name='所属测试'),
        ),
        migrations.AddField(
            model_name='inducation',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inducation_test', to='question.Test', verbose_name='所属测试'),
        ),
    ]
