# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-24 01:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='name',
            new_name='title',
        ),
    ]
