# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-26 01:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20180224_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_test', to='question.Test', verbose_name='所属测试'),
        ),
    ]
