# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-28 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_inducation_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='option',
        ),
        migrations.AddField(
            model_name='result',
            name='score',
            field=models.IntegerField(default=0, verbose_name='分值'),
        ),
    ]
