# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-28 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0007_auto_20180228_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='score',
            field=models.IntegerField(blank=True, null=True, verbose_name='分值'),
        ),
    ]
