# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-10 01:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wechat_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('openid', models.CharField(blank=True, max_length=50, null=True, verbose_name='OPENID')),
                ('unionid', models.CharField(max_length=50, unique=True, verbose_name='UNIONID')),
                ('nickname', models.CharField(max_length=50, verbose_name='昵称')),
                ('sex', models.CharField(blank=True, max_length=1, null=True, verbose_name='性别')),
                ('province', models.CharField(blank=True, max_length=50, null=True, verbose_name='省份')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='城市')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='国家')),
                ('headimgurl', models.URLField(blank=True, null=True, verbose_name='头像')),
                ('language', models.CharField(blank=True, max_length=10, null=True, verbose_name='语言')),
                ('privilege', models.CharField(blank=True, max_length=50, null=True, verbose_name='特权用户')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wechatuser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-create_time'],
                'verbose_name_plural': '微信用户表',
                'verbose_name': '微信用户表',
            },
        ),
    ]
