# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-23 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechat_user',
            name='unionid',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='UNIONID'),
        ),
    ]
